# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"

  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: /uploads/cache

  loaders:
    default:
      filesystem:
        data_root: "%kernel.project_dir%/public/uploads" # ~ # %kernel.project_dir%/public

  cache: default
  data_loader: default

  controller:
    filter_action: liip_imagine.controller:filterAction
    filter_runtime_action: liip_imagine.controller:filterRuntimeAction
    redirect_response_code: 301

  webp:
    generate: false
    quality: 100
    cache: ~
    data_loader: ~
    post_processors: [ ]

  default_filter_set_settings:
    quality: 100
    jpeg_quality: ~
    png_compression_level: ~
    png_compression_filter: ~
    animated: false
    format: ~
    cache: ~
    data_loader: ~
    default_image: null
    filters: [ ]
    post_processors: [ ]

  filter_sets:
    # the name of the "filter set"
    thumbnail:
      # adjust the image quality to 75%
      quality: 75
      # list of transformations to apply (the "filters")
      filters:
        # create a thumbnail: set size to 120x90 and use the "outbound" mode
        # to crop the image when the size ratio of the input differs
        thumbnail: { size: [ 120, 90 ], mode: outbound }
        # create a 2px black border: center the thumbnail on a black background
        # 4px larger to create a 2px border around the final image
        # background: { size: [ 124, 94 ], position: center, color: '#000000' }
    productImagesThumbnails:
      quality: 100
      filters:
        downscale:
          max: [ 600, 600 ]

    servicesThumbnails:
      quality: 100
      filters:
        downscale:
          max: [ 380, 220 ]
    mobile:
      quality: 100
      filters:
        downscale:
          max: [ 480, 270 ]
    tablet:
      quality: 100
      filters:
        downscale:
          max: [ 720, 405 ]
    desktop:
      quality: 100
      filters:
        downscale:
          max: [ 1920, 1080 ]
